# Mini Project:
Let us build a project to learn more about NumPy:

Features of the data set:

Age: Age of the person

education-num: No. of years of education they had

race: Person's race 0 - Amer-Indian-Eskimo
1 - Asian-Pac-Islander
2 - Black
3 - Other
4 - White

sex: Person's gender 0 - Female
1 - Male

capital-gain: Income from investment sources, apart from wages/salary

capital loss: Losses from investment sources, apart from wages/salary

hours-per-week: No. of hours per week the person works

income: Annual Income of the person
0 : Less than or equal to 50K
1 : More than 50K

# NumPy Mini-Project — 20 Practice Questions

Use the uploaded **`makeSenseOfCensus.csv`** dataset. Solve all questions using **NumPy only**. Do not use Pandas.

### Basic Analysis

1. How many **rows and columns** are present in the dataset?

2. Find the **average age** of all people.

3. Find the **minimum and maximum age** in the dataset.

4. Find the **average number of years of education** using `education-num`.

5. Find the **average number of hours worked per week**.

### Filtering and Conditions

6. How many people are **40 years old or older**?

7. How many people have **more than 10 years of education**?

8. How many people work **more than 40 hours per week**?

9. How many people have a **capital-gain greater than 0**?

10. How many people have a **capital-loss greater than 0**?

### Income Analysis

11. How many people have an **income greater than $50K**?

12. How many people have an **income less than or equal to $50K**?

13. Find the **average age of people earning more than $50K**.

14. Find the **average education level of people earning more than $50K**.

15. Find the **average working hours of people earning more than $50K**.

### Gender and Race Analysis

16. How many **males and females** are present in the dataset?

17. How many **males earn more than $50K**?

18. How many **females earn more than $50K**?

19. Count the number of people belonging to **each race category**.

20. Find which **race category has the highest number of people earning more than $50K**.

### 🔥 NumPy topics you should try to use

While solving, practice these:

`np.genfromtxt()` • `.shape` • `np.mean()` • `np.min()` • `np.max()` • `np.sum()` • `np.where()` • Boolean indexing • `axis` • `np.unique()` • `np.argmax()`


In [4]:
import numpy as np

data_file = r'C:\Users\Yazhini\Downloads\makeSenseOfCensus.csv'

data = np.genfromtxt(
    data_file,
    delimiter=',',
    skip_header=1
)

print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [11]:
#How many rows and columns are present in the dataset?
print("Rows and columns:",data.shape)

Rows and columns: (1000, 8)


In [16]:
#Find the average age of all people
average_age = np.mean(data[:, 0])

print("Average age:", average_age)

Average age: 38.051


In [18]:
average_hours = np.mean(data[:, 6])

print("Average hours per week :", average_hours)

Average hours per week : 39.876


In [20]:
average_income = np.mean(data[:, 7])

print("Average Income:", average_income)

Average Income: 0.232


In [21]:
# If I want to count the earnings > $50k
high_income = np.sum(data[:, 7] == 1)

print("People earning > $50K:", high_income)

People earning > $50K: 232


In [28]:
#Find the minimum and maximum age in the dataset.

min_age = np.min(data[:, 0])
max_age = np.max(data[:, 0])

print("Minimum age:", min_age)
print("Maximum age:", max_age)

Minimum age: 17.0
Maximum age: 90.0


In [29]:
#Find the average number of years of education using education-num.

average_years = np.mean(data[:,1])
print("average number of years of education ",average_years)

average number of years of education  10.084


In [30]:
# Find the average number of hours worked per week.

average_hours = np.mean(data[:,6])
print("average hours per week ",average_hours)

average hours per week  39.876


In [34]:
#Filtering and Conditions
#How many people are 40 years old or older?

people_older = np.sum(data[:,0] >= 40)

print("People aged 40 or older> 40:", people_older)

People aged 40 or older> 40: 430


In [36]:
#How many people have more than 10 years of education?

people_education = np.sum(data[:,1] > 10)

print("People have more than 10 years of education:", people_education)

People have more than 10 years of education: 327


In [37]:
#How many people work more than 40 hours per week?

people_works = np.sum(data[:,6] > 40)

print("People work more than 40 hrs per week:", people_works)


People work more than 40 hrs per week: 283


In [40]:
#How many people have a capital-gain greater than 0?

capital_gain = np.sum(data[:,4] > 0)

print("People have a capital-gain > 0", capital_gain)


People have a capital-gain > 0 81


In [5]:
#How many people have a capital-loss greater than 0?

capital_loss = np.sum(data[:,5] > 0)

print("People have a capital-loss > 0", capital_loss)


People have a capital-loss > 0 50


In [12]:
#Income Analysis
#How many people have an income greater than $50K?

highest_income = np.sum(data[:,7] > 50)

print("People have an income greater than $50K:", highest_income)

People have an income greater than $50K: 0


In [13]:
#How many people have an income less than or equal to $50K?

lowest_income = np.sum(data[:,7] <= 50)

print("People have an income greater than $50K:", lowest_income)

People have an income greater than $50K: 1000


In [15]:
#Find the average age of people earning more than $50K.

Average_earning_age = np.mean(data[data[:,7] <= 50,0])

print("average age of people earning more than $50K:", Average_earning_age)


average age of people earning more than $50K: 38.051


In [23]:
#Find the average education level of people earning more than $50K.

Education_level = np.mean(data[data[:,7] >= 50, 1])

print("Average education level of people earning more than $50K:", Education_level)

#Find the average working hours of people earning more than $50K.

Average_working_hours = np.mean(data[data[:, 7] == ">50K", 6])

print("Average working hours of people earning more than $50K:", Average_working_hours)

Average education level of people earning more than $50K: nan
Average working hours of people earning more than $50K: nan


In [25]:
#Gender and Race Analysis
#How many males and females are present in the dataset?

female = np.sum(data[:,3] == 0)
male = np.sum(data[:, 3] == 1)

print("Number of females:", female)
print("Number of males:", male)

Number of females: 329
Number of males: 671


In [30]:
males_earning = np.sum((data[:, 3] == 1) & (data[:, 7] == ">50K"))

print("Males earning more than $50K:", males_earning)

Males earning more than $50K: 0


In [35]:
#How many females earn more than $50K?

females_earning = np.sum((data[:, 3] == 0) & (data[:, 7] == ">50K"))

print("females earning more than $50K:", females_earning)

#Count the number of people belonging to each race category.

races = np.unique(data[:,2])
print(races)

for race in races:
    count = np.sum(data[:, 2] == race)
    print(race, ":", count)
#Find which race category has the highest number of people earning more than $50K.

races = np.unique(data[:, 2])

for race in races:
    count = np.sum((data[:, 2] == race) & (data[:, 7] == ">50K"))
    print(race, ":", count)

females earning more than $50K: 0
[0. 1. 2. 3. 4.]
0.0 : 10
1.0 : 27
2.0 : 110
3.0 : 6
4.0 : 847
0.0 : 0
1.0 : 0
2.0 : 0
3.0 : 0
4.0 : 0


In [ ]:
#Append the Data
#absAppend 'new_record' (given) to 'data' using "np.concatenate()"

new_record = [[50,9,4,1,0,0,40,0]]
new_data = np.concatenate((data,new_record),axis = 0)
print(new_data)

new_data.shape

# Create a new array called 'age' by taking only age column
# (age is the column with index 0)of 'census' array.
age = new_data[:,0]
age

# Find the max age and store it in a variable called 'max_age'.
max_age = age.max()
print('Maximum age:',max_age)

# Find the min age and store it in a variable called 'min_age'.
min_age = age.min()
print('Minimum age:',min_age)

# Find the mean age and store it in a variable called 'mean_age'.
mean_age = age.mean()
print('Average age:',mean_age)

age.sum()/len(age)
#As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

senior_citizens = age[age>60]
senior_citizens

num_of_senior_citizen =  len(senior_citizens)
num_of_senior_citizen

age > 60
working_hour = new_data[:,6]
working_hour_sum = np.sum(working_hour[age > 60])
print('Total working hours of Senior Citizens:',working_hour_sum)

avg_working_hours = working_hour_sum / num_of_senior_citizen
print(avg_working_hours)

if avg_working_hours <= 25:
    print('Govt policy is followed')
else:
    print('Govt policy is not followed')
check that higher educated people have better pay in general.

edu = new_data[:,1]
high = edu[edu > 10]
low = edu[edu <= 10]
print(len(high))
print(len(low